**QUESTION 2**

Write a python code to filter the given image using following size of the filters (receptive field) and hyperparameters

 (i) filter size (3x3) and (5x5), stride=1 
 
 (ii) filter size (3x3) and (5x5), stride=2
 
  (iii) filter size (3x3) and (5x5), stride=1, zero-padding

In [1]:
from PIL import Image, ImageOps
from numpy import asarray 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import cv2
from skimage.measure import shannon_entropy

In [2]:
def processImage(image): 
  image = cv2.imread('/content/sample_data/IMAGE.jpeg', 1) 
  image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY) 
  return image

In [3]:
def convolve(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [4]:
img = Image.open('/content/sample_data/IMAGE.jpeg')
img_gray = ImageOps.grayscale(img)
image = asarray(img_gray)
print(image.shape)
entropy = shannon_entropy(image)
print("Entropy of original image = {}".format(entropy))

(378, 378)
Entropy of original image = 7.909537771496434


In [5]:
#3*3 Box Filter (stride=1)
kernel = np.ones((3,3), np.int16)
image1 = convolve(image,kernel,padding=1,strides = 1)
print(image1.shape)
entropy1 = shannon_entropy(image1)
print("Entropy = {}".format(entropy1))

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 233. 223. ... 179. 174.   0.]
 [  0. 224. 223. ... 144. 132.   0.]
 ...
 [  0. 108. 118. ... 205. 199.   0.]
 [  0. 121. 125. ... 197. 189.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
(378, 378)
Entropy = 10.967790004273695


In [6]:
#5x5 Box Filter (stride=1)
kernel = np.ones((5,5), np.int16)
image1 = convolve(image,kernel,padding=1,strides = 1)
print(image1.shape)
entropy2 = shannon_entropy(image1)
print("Entropy = {}".format(entropy2))

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 233. 223. ... 179. 174.   0.]
 [  0. 224. 223. ... 144. 132.   0.]
 ...
 [  0. 108. 118. ... 205. 199.   0.]
 [  0. 121. 125. ... 197. 189.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
(376, 376)
Entropy = 12.35960669992535


In [7]:
#3x3 Box Filter (stride=2)
kernel = np.ones((3,3), np.int16)
image1 = convolve(image,kernel,padding=1,strides = 2)
print(image1.shape)
entropy3 = shannon_entropy(image1)
print("Entropy = {}".format(entropy3))

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 233. 223. ... 179. 174.   0.]
 [  0. 224. 223. ... 144. 132.   0.]
 ...
 [  0. 108. 118. ... 205. 199.   0.]
 [  0. 121. 125. ... 197. 189.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
(189, 189)
Entropy = 3.568078059839491


In [8]:
#5x5 Box Filter (stride=2)
kernel = np.ones((5,5), np.int16)
image1 = convolve(image,kernel,padding=1,strides = 2)
print(image1.shape)
entropy4 = shannon_entropy(image1)
print("Entropy = {}".format(entropy4))

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 233. 223. ... 179. 174.   0.]
 [  0. 224. 223. ... 144. 132.   0.]
 ...
 [  0. 108. 118. ... 205. 199.   0.]
 [  0. 121. 125. ... 197. 189.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
(188, 188)
Entropy = 3.802782444900707


In [9]:
#3x3 Box Filter (stride=1 and zero padding)
kernel = np.ones((3,3), np.int16)
image1 = convolve(image,kernel,padding=0,strides = 1)
print(image1.shape)
entropy5 = shannon_entropy(image1)
print("Entropy = {}".format(entropy5))

(376, 376)
Entropy = 10.999291813255514


In [10]:
#5x5 Box Filter (stride=1 and zero padding)
kernel = np.ones((5,5), np.int16)
image1 = convolve(image,kernel,padding=0,strides = 1)
print(image1.shape)
entropy6 = shannon_entropy(image1)
print("Entropy = {}".format(entropy6))

(374, 374)
Entropy = 12.406467115978865


In [11]:
numpyArray = np.array([[entropy], [entropy1], [entropy2], [entropy3], [entropy4], [entropy5], [entropy6]]) 
df = pd.DataFrame(data = numpyArray,  
                        index = ["Image", "3x3(strides=1)", "5x5(strides=1)","3x3(strides=2)", "5x5(strides=2)", "3x3(strides=1 and zero padding)", "5x5(strides=1 and zero padding)"],  
                        columns = ["Entropy"])
df

Entropy
Image                             7.909538
3x3(strides=1)                   10.967790
5x5(strides=1)                   12.359607
3x3(strides=2)                    3.568078
5x5(strides=2)                    3.802782
3x3(strides=1 and zero padding)  10.999292
5x5(strides=1 and zero padding)  12.406467